Controllers/Master/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPayroll.Models.Admin;
using WebPayroll.Models.Master;

namespace WebPayroll.Controllers.Master
{
    [Authorize]//102
    public class BranchController : Controller
    {
        // GET: Branch
        public ActionResult Index()
        {
            if (User.IsInRole("Admin") || AppsUserRepository.RightList(User.Identity.Name).Contains("M002"))
            { return View(); }
            else { return View("_Security"); }
        }

        [HttpPost]
        public JsonResult List(int status = 0, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                BranchRepository dal = new BranchRepository();
                List<BranchModel> model = new List<BranchModel>();
                model = dal.GetAll().ToList();
                int count = model.Count;
                model = model.OrderBy(x => x.Name).ToList();
                List<BranchModel> Model1 = model.Skip(jtStartIndex).Take(jtPageSize).ToList();
                return Json(new { Result = "OK", Records = Model1, TotalRecordCount = count });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Create(BranchModel model)
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    BranchRepository dal = new BranchRepository();
                    dal.Insert(model);
                    return Json(new { Result = "OK", Record = model });
                }
                else
                {
                    return Json(new { Result = "Error", Message = "Sorry, You are not Authorized to do this action" });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Update(BranchModel model)
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    BranchRepository dal = new BranchRepository();
                    dal.Edit(model);
                    return Json(new { Result = "OK", Record = model });
                }
                else
                {
                    return Json(new { Result = "Error", Message = "Sorry, You are not Authorized to do this action" });
                }
                
            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetBranchOptions()
        {
            List<BranchModel> model = new List<BranchModel>();
            model.Add(new BranchModel { Id = 0, Code = "* Select *" });
            var data = model.Select(c => new { DisplayText = c.Code, Value = c.Id });
            try
            {
                BranchRepository dal = new BranchRepository();
                var list = dal.GetAll()
                                .Select(c => new { DisplayText = c.Code, Value = c.Id });
                return Json(new { Result = "OK", Options = list.Concat(data).OrderBy(x => x.DisplayText) });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetBranchNameOptions()
        {
            List<BranchModel> model = new List<BranchModel>();
            model.Add(new BranchModel { Id = 0, Name = "* Select *" });
            var data = model.Select(c => new { DisplayText = c.Name, Value = c.Id });
            try
            {
                BranchRepository dal = new BranchRepository();
                var list = dal.GetAll()
                                .Select(c => new { DisplayText = c.Name, Value = c.Id });
                return Json(new { Result = "OK", Options = list.Concat(data).OrderBy(x => x.DisplayText) });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

Views/Branch/Index.cshtml
@using WebPayroll.Helper
@{
    ViewBag.Title = "Branch Name";
}
<style>
    input, select, textarea {
        max-width: 180px;
    }
</style>

<div class="panel panel-info topmar-10">
    <div class="panel-heading">
        @Html.MyActionLink("<span class='fa fa-dashboard fa-1x'> Dashboard</span>", "Dashboard", "Index", "Home", null, new { @class = "btn btn-info btn-sm" })
        <div class="btn-group dropdown">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Quick Link
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.MyActionLink("<span class='fa fa-building fa-1x'> Branch</span>", "Branch", "Index", "Branch", null, new { @class = "btn btn-link btn-sm" })</li>
                <li>@Html.MyActionLink("<span class='fa fa-list fa-1x'> Department</span>", "Department", "Index", "Department", null, new { @class = "btn btn-link btn-sm" })</li>
                <li>@Html.MyActionLink("<span class='fa fa-tag fa-1x'> Designation</span>", "Designation", "Index", "Designation", null, new { @class = "btn btn-link btn-sm" })</li>
                <li>@Html.MyActionLink("<span class='fa fa-user fa-1x'> Employee</span>", "Employee", "Index", "Employee", null, new { @class = "btn btn-link btn-sm" })</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <div id="table"></div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {

        $('#table').jtable({
            title: 'Branch Name',
            paging: true,
            pagesize: 3,
            sorting: true,
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '@Url.Action("List")',
                updateAction: '@Url.Action("Update")',
                createAction: '@Url.Action("Create")'
            },
            fields: {
                Id: {
                    title: 'Id',
                    width:'1%',
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Code: {
                    title: 'Code',
                    width: '1%'
                },
                Name: {
                    title: 'Name',
                    width: '1%'
                },
            },
            formCreated: function (event, data) {
                data.form.validationEngine();
            },
            formSubmitting: function (event, data) {
                return data.form.validationEngine('validate');
            },
            formClosed: function (event, data) {
                data.form.validationEngine('hide');
                data.form.validationEngine('detach');
            }
        });
        $('#table').jtable('load');
    });
</script>