Controllers/Admin/AppsUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPayroll.DAL.Master;
using WebPayroll.Models.Admin;

namespace WebPayroll.Controllers.Admin
{
    [Authorize]
    public class AppsUserController : Controller
    {
        // GET: AppsUser
        // View Employee
        public ActionResult Index()
        {
            ViewBag.status = new SelectList(new[] {
                new SelectListItem{Value="1", Text="Active"},
                new SelectListItem{Value="2", Text="InActive"},
                }, "Value", "Text");

            if (User.IsInRole("Admin")) { return View(); }
            else { return View("_Security");}              
        }

        [HttpPost]
        public JsonResult List(string name = null, int status = 0, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                AppsUserRepository dal = new AppsUserRepository();
                List<AppsUserModel> model = new List<AppsUserModel>();

                if (string.IsNullOrEmpty(name))
                {
                    model = dal.GetAll().ToList();
                }
                else
                {
                    model = dal.GetAll().Where(x => (x.Name + " " + x.AppLogin).ToLower().Contains(name.ToLower())).ToList();
                }
                if (status != 0)
                {
                    model = model.Where(x => x.Status == status).ToList();
                }
                int count = model.Count;
                model = model.OrderBy(x => x.Name).ToList();
                List<AppsUserModel> Model1 = model.Skip(jtStartIndex).Take(jtPageSize).ToList();
                return Json(new { Result = "OK", Records = Model1, TotalRecordCount = count });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Create(AppsUserModel model)
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    AppsUserRepository dal = new AppsUserRepository();
                    if (dal.IsUserExist(model.AppLogin) ==true)
                    {
                        return Json(new { Result = "ERROR", Message = "Email id already bind with other user,Please use other!" });
                    }
                    dal.Insert(model);
                    return Json(new { Result = "OK", Record = model });
                }
                else
                {
                    return Json(new { Result = "Error", Message = "Sorry, You are not Authorized to do this action" });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Update(AppsUserModel model)
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    if (!ModelState.IsValid)
                    {
                        return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                    }
                    AppsUserRepository dal = new AppsUserRepository();
                    dal.Edit(model);
                    return Json(new { Result = "OK", Record = model });
                }
                else
                {
                    return Json(new { Result = "Error", Message = "Sorry, You are not Authorized to do this action" });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetEmployeeOptions()
        {
            try
            {
                AppsUserRepository dal = new AppsUserRepository();
                var list = dal.GetAll()
                                .Select(c => new { DisplayText = c.Name, Value = c.Id });
                return Json(new { Result = "OK", Options = list });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public ActionResult GetEmployee()
        {
            try
            {
                AppsUserRepository dal = new AppsUserRepository();
                var list = from m in dal.GetAll().OrderBy(x => x.Name)
                           select new { Id = m.Id, Name = m.Name };
                return Json(list, "employee", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public ActionResult AddEmpRights(string id, string list)
        {
            AppsUserRepository.AddEmpRights(Convert.ToInt32(id), list);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetEmpRights(int id = 0)
        {
            AppsUserRepository dal = new AppsUserRepository();
            try
            {
                var data = dal.GetById(id).UserRight.ToList();

                return Json(new { Result = "OK", Records = data });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult ListOfEmpRights(int id = 0, string menu = null, int jtStartIndex = 0, int jtPageSize = 0)
        {
            AppsUserRepository dal = new AppsUserRepository();
            UserRightRepository cdal = new UserRightRepository();
            try
            {
                var empRights = dal.GetById(id).UserRight;
                var rightId = from c in empRights
                              select c.Id;

                var list = cdal.GetAll().Where(c => !rightId.Contains(c.Id)).ToList();
                if (!string.IsNullOrEmpty(menu))
                {
                    list = list.Where(x => x.MnuName == menu).ToList();
                }
                int count = list.Count;
                var Model1 = list.Skip(jtStartIndex).Take(jtPageSize).ToList();
                return Json(new { Result = "OK", Records = Model1, TotalRecordCount = count });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetEmpRightsOptions(int id = 0)
        {
            AppsUserRepository dal = new AppsUserRepository();
            UserRightRepository cdal = new UserRightRepository();
            try
            {
                if (id == 0)
                {
                    var curr = cdal.GetAll()
                               .Select(c => new { DisplayText = c.Description, Value = c.Id });
                    return Json(new { Result = "OK", Options = curr });
                }
                else
                {
                    var curr = dal.GetById(id).UserRight
                               .Select(c => new { DisplayText = c.Description, Value = c.Id });
                    return Json(new { Result = "OK", Options = curr });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        //View Employee Rights Page, Only for Admin
        public ActionResult UserRightsList(int id)
        {
            if (User.IsInRole("Admin"))
            {
                AppsUserRepository dal = new AppsUserRepository();
                ViewBag.Employee = new SelectList(dal.GetAll().Where(x => x.Id == id && x.Role != "Admin"), "Id", "Name");

                ViewBag.menu = new SelectList(new[] {
                new SelectListItem{Value="MASTER", Text="MASTER"},
                new SelectListItem{Value="TRANSACTION", Text="TRANSACTION"},
                new SelectListItem{Value="REPORT", Text="REPORT"},
                }, "Value", "Text");

                return PartialView();
            }
            else
            {
                return View("Security");
            }
        }

        public JsonResult DeleteRights(UserRightModel model, int empId)
        {
            try
            {

                if (User.IsInRole("Admin") || UserRightRepository.RightList(User.Identity.Name).Contains("R009"))
                {
                    AppsUserRepository.DeleteRights(empId, model.Id);
                    return Json(new { Result = "OK", Record = model });
                }
                else
                {
                    return Json(new { Result = "Error", Message = "Sorry, You are not Authorized to do this action" });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "Error", Message = ex.Message });
            }
        }

        
    }
}

Views/AppsUser/Index.cshtml
@using WebPayroll.Helper
@{
    ViewBag.Title = "Application User";
}


<div class="panel panel-info topmar-10">
    <div class="panel-heading">
        @Html.MyActionLink("<span class='fa fa-dashboard fa-1x'></span> Dashboard", "Dashboard", "Index", "Home", null, new { @class = "btn btn-info btn-sm" })
        @Html.MyActionLink("<span class='fa fa-building fa-1x'></span> Company", "Company", "Index", "Company", null, new { @class = "btn btn-info btn-sm" })
        @Html.MyActionLink("<span class='fa fa-lock fa-1x'></span> Form List", "Add forms for authorizaton", "Index", "UserRights", null, new { @class = "btn btn-info btn-sm" })
        @Html.DropDownList("status", new SelectList((ViewBag.status) as SelectList, "Value", "Text"), new { @class = "search-box" })
        <input type="text" class="search-box" id="name" placeholder="Search.." />
        <button id="search" type="button" class="btn btn-info btn-sm">
            <span class="glyphicon glyphicon-search"></span> Search
        </button>
    </div>
    <div class="panel-body">
        <div id="table"></div>
        <div id="dialog-edit" style="display: none"></div>
        <div id="dialog-client" style="display: none"></div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        //Dialog form
        $("#dialog-edit").dialog({
            title: 'Add',
            autoOpen: false,
            resizable: false,
            width: 600,
            show: { effect: 'drop', direction: "up" },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(".ui-dialog-titlebar-close").show();
                $(this).load(url);
            },
        });

        $('#table').jtable({
            title: 'Application Users',
            paging: true,
            pagesize: 3,
            sorting: false,
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '@Url.Action("List")',
                updateAction: '@Url.Action("Update")',
                createAction: '@Url.Action("Create")'
            },
            fields: {
                Id: {
                    title: 'Id',
                    width: '1%',
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Code: {
                    title: 'Code',
                    width: '1%'
                },
                Name: {
                    title: 'Name',
                    width: '2%'
                },
                AppLogin1: {
                    title: 'CreateLogin',
                    width: '0.1%',
                    create: false,
                    edit: false,
                    display: function (d) {
                        if (d.record.Status == 2) {
                            var $img = $('<div class="text-center pointer"><i title="Create Login" class="fa fa-lock text-info fa-2x"></div>');
                            $img.click(function () {
                                var file = d.record.AppLogin;
                                var url = "Account/Register?applogin=" + file;
                                window.open(url);
                            });
                            return $img
                        }
                    }
                },
                AppLogin: {
                    title: 'Emailid',
                    width: '3%',
                },
                Role: {
                    title: 'Role',
                    width: '1%',
                    edit: false,
                    create: false,
                },
                Status: {
                    title: 'Status',
                    width: '0.1%',
                    create: false,
                    options: { '1': 'Active', '2': 'InActive' },
                    defaultValue: '1',
                    display: function (data) {
                        if (data.record.Status == 1)
                            return "<div class='green'>" + 'Active' + "</div>";
                        if (data.record.Status == 2)
                            return "<div class='red'>" + 'InActive' + "</div>";
                    },
                },
                Rights: {
                    title: '',
                    width: '0.1%',
                    sorting: false,
                    create: false,
                    edit: false,
                    listClass: 'child-opener-image-column',
                    display: function (rights) {
                        if (rights.record.Role != "Admin")
                        {
                            var $img = $('<i title="Assigned Rights" class="fa fa-key fa-1x text-primary pointer"/>');
                            $img.click(function () {
                                $('#table').jtable('openChildTable', $img.closest('tr'),
                                {
                                    title: rights.record.Name + " - Rights",
                                    actions: {
                                        listAction: '@Url.Action("GetEmpRights")?id=' + rights.record.Id,
                                        deleteAction: '@Url.Action("DeleteRights")?empId=' + rights.record.Id,
                                    },
                                    fields: {
                                        Id: {
                                            title: 'Id',
                                            width: '1%',
                                            key: true,
                                            create: false,
                                            edit: false,
                                            list: false
                                        },
                                        MnuName: {
                                            title: 'MnuName',
                                            width: '12%'
                                        },
                                        TableName: {
                                            title: 'TableName',
                                            width: '12%'
                                        },
                                        Description: {
                                            title: 'Description',
                                            width: '12%'
                                        },
                                    },
                                    toolbar: {
                                        items: [{
                                            icon: '/Content/themes/base/images/Add.png',
                                            text: 'Assign User Rights',
                                            click: function () {
                                                url = $('@Html.ActionLink("Assigned EmpRights", "UserRightsList")').attr('href');
                                                url = url + "?id=" + rights.record.Id,
                                                $("#dialog-edit").dialog("option", "title", "Assign Rights");
                                                $("#dialog-edit").dialog('open');
                                                return false;
                                            }
                                        }]
                                    }
                                }, function (data) {
                                    data.childTable.jtable('load');
                                });
                            });
                            return $img;
                        }
                    }
                },
            },
            formCreated: function (event, data) {
                data.form.find('input[name="Name"]').addClass('validate[required]');
                data.form.validationEngine();
            },
            formSubmitting: function (event, data) {
                return data.form.validationEngine('validate');
            },
            formClosed: function (event, data) {
                data.form.validationEngine('hide');
                data.form.validationEngine('detach');
            }
        });
        $('#table').jtable('load');

        $("#refresh").click(function (e) {
            $('#name').val('');
            $("#spin").addClass("spin");
            e.preventDefault();
            $('#table').jtable('load');
            $("#spin").removeClass("spin");
        });
        $("#search").click(function (e) {
            e.preventDefault();
            $('#table').jtable('load', {
                name: $('#name').val(), status: $('#status').val()
            });
        });

        $('#name').bind('keyup', function (e) {
            if (e.which == 13) {
                $('#table').jtable('load', {
                    name: $('#name').val(), status: $('#status').val()
                });
            }
        });
    });
</script>

Views/AppsUser/UserRightsList.cshtml
@{
    ViewBag.Title = "UserRightsList";
}

<div class="panel panel-info">
    <div class="panel-heading">
        Users: @Html.DropDownList("Employee", new SelectList((ViewBag.Employee) as SelectList, "Value", "Text"), new { @class = "search-box" })
        @Html.DropDownList("menu", new SelectList((ViewBag.menu) as SelectList, "Value", "Text"), "Select Menu", new { @class = "search-box" })
        <button role="button" class="btn btn-success btn-xs" id="EmpRights" title="Add Rights">
            <span class="fa fa-plus"></span>  Add
        </button>
    </div>
    <div class="panel-body">
        <div id="rightsTable"></div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#rightsTable').jtable({
            title: 'Employee Rights',
            paging: true,
            pagesize: 3,
            sorting: true,
            selecting: true,
            multiselect: true,
            selectOnRowClick:false,
            selectingCheckboxes: true,
            actions: {
                listAction: '@Url.Action("ListOfEmpRights")'
            },
            fields: {
                Id: {
                    title: 'Id',
                    width: '1%',
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                MnuName: {
                    title: 'MnuName',
                    width: '12%'
                },
                TableName: {
                    title: 'TableName',
                    width: '12%'
                },
                Operation: {
                    title: 'Operation',
                    width: '12%'
                },
            },
            selectionChanged: function () {
                var $selecedRows = $('#rightsTable').jtable('selectedRows');
                if ($selecedRows.length != 0) {
                    $('#EmpRights').prop('disabled', false);
                }
                else {
                    $('#EmpRights').prop('disabled', false);
                }
            }
        });
        $('#rightsTable').jtable('load', { id: $('#Employee').val() });

        $("#menu").change(function (e) {
            e.preventDefault();
            $('#rightsTable').jtable('load', {
                id: $('#Employee').val(), menu: $('#menu').val()
            });
        });

        //Delete selected currencies
        $('#EmpRights').button().click(function () {
            var emp = $("#Employee").val();
            var $selecedRows = $('#rightsTable').jtable('selectedRows');
            var list = emp;
            $selecedRows.each(function () {
                var record = $(this).data('record');
                list = list + "," + record.Id;
            });
            $.ajax({
                url: "@Url.Action("AddEmpRights", "AppsUser")",
                type: 'POST',
                datatype: 'HTML',
                data: { id: emp, list: list },
                success: function (data) {
                    alert("Right Assigned");
                    $('#rightsTable').jtable('load', {
                        id: $('#Employee').val()
                    });
                },
                error: function () {
                }
            });
        });
    });
</script>